### ISSUE TITLE
Multi server support?

### ISSUE THREAD

**Issue by bjompen** [PowershellGroup/PoshToDon#1]
Since a user can have multiple accounts it could be useful to change the `$script:auth` variable to something like a hashtable where key is the instance name and value is the auth token and metadata.

Also if a "default" setting is added it supports silently using one standard host, yet store multiple accounts.

```PowerShell
@{
    host1.mastodon.abc = @{
        auth = @{
            access_token = "abcdefghijklmnopqrstuvademakaroner"
            token_type = "Bearer"
            scope = "write"
            created_at = 1234567890
        }
        default = $true
    }
    host2.mstdn.xyz = @{
        auth = @{
            access_token = "abcdefghijklmnopqrstuvademakaroner"
            token_type = "Bearer"
            scope = "read"
            created_at = 1234567890
        }
        default = $false
    }
}
```

**Comment by SeidChr** [comment]
thought about returning a session variable and require to pass it in with every followup command.
So that you could authenticate with multiple servers sequentially and select the correct one by passing in the session object

**Comment by SeidChr** [comment]
@bjompen can you review the request?
